### ISSUE TITLE
Alternative to hash-lang line

### ISSUE THREAD

**Issue by fiddlerwoaroof** [ruricolist/vernacular#1]
Would it be possible to support the hello-emacs lines as an alternative way to specify the language used to interpret the file? e.g. ```;; -*- mode: my-language; package: foo.bar -*-```  Since a lot of Common Lisp development occurs in emacs anyways, this would allow for a more integrated development experience.

**Comment by ruricolist** [comment]
I have considered it. I worry about conflicts. I know there are editors out there that actually care about the file-local value of `Package` -- whatever Edi Weitz uses -- but I think they use uppercase to avoid conflict with Emacs.

Are you suggesting `mode:` or `package:` to designate the language?

**Comment by fiddlerwoaroof** [comment]
I was thinking of using `mode:`

**Comment by fiddlerwoaroof** [comment]
That way, if I have an emacs mode for my language, I’ll get the right emacs editing experience. This would make emacs work a bit like DrRacket does.

**Comment by ruricolist** [comment]
So if you have a mode line like

    ;; -*- mode: my-language-mode; package: foo.bar -*-

It would be equivalent to 

    #lang my-language

It sounds reasonable. I actually wrote a file local variable parser a while ago for something else. I'll poke around and see if I still have the code.

**Comment by ruricolist** [comment]
I’ve committed a parser for file locals (it’s not complicated, but there are some corner cases if you want to be compatible with Emacs). But I haven’t decided yet what the precedence of the mode should be, relative to other ways of designating a language, and whether it should be used as-is or there should be a translation mechanism (so that e.g. sql-mode would be handled by cl-yesql).
